# stolen from https://github.com/rust-lang/mdBook/wiki/Automated-Deployment%3A-GitHub-Actions#github-pages-deploy
name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install mdbook
      run: |
        mkdir mdbook
        name=mdbook
        version=v0.4.27
        curl --silent --show-error --location https://github.com/rust-lang/$name/releases/download/$version/$name-$version-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        echo `pwd`/$name >> $GITHUB_PATH
    - name: Install mdbook-mermaid
      run: |
        name=mdbook-mermaid
        version=v0.12.6
        curl --silent --show-error https://github.com/badboy/$name/releases/download/$version/$name-$version-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        echo `pwd`/$name >> $GITHUB_PATH
    - name: Install mdbook-toc
      run: |
        name=mdbook-toc
        version=0.11.2
        curl --silent --show-error https://github.com/badboy/$name/releases/download/$version/$name-$version-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        echo `pwd`/$name >> $GITHUB_PATH
    - name: Install mdbook-admonish
      run: |
        name=mdbook-admonish
        version=v1.8.0
        curl --silent --show-error https://github.com/tommilligan/$name/releases/download/$version/$name-$version-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        echo `pwd`/$name >> $GITHUB_PATH
    - name: Deploy GitHub Pages
      run: |
        mdbook build
        git worktree add gh-pages
        git config user.name "Deploy from CI"
        git config user.email ""
        cd gh-pages
        # Delete the ref to avoid keeping history.
        git update-ref -d refs/heads/gh-pages
        rm -rf *
        mv ../book/* .
        git add .
        git commit -m "Deploy $GITHUB_SHA to gh-pages"
        git push --force --set-upstream origin gh-pages
