# stolen from https://github.com/rust-lang/mdBook/wiki/Automated-Deployment%3A-GitHub-Actions#github-pages-deploy
name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install mdbook
      run: |
        mkdir mdbook
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.27/mdbook-v0.4.27-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        echo `pwd`/mdbook >> $GITHUB_PATH
    - name: Install mdbook-mermaid
      run: |
        name=mdbook-mermaid
        curl -sSL https://github.com/badboy/$name/releases/download/v0.12.6/$name-v0.12.6-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        echo `pwd`/$name >> $GITHUB_PATH
    - name: Install mdbook-toc
      run: |
        name=mdbook-toc
        curl -sSL https://github.com/badboy/$name/releases/download/0.11.2/$name-0.11.2-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        echo `pwd`/$name >> $GITHUB_PATH
    - name: Install mdbook-admonish
      run: |
        name=mdbook-admonish
        curl -sSL https://github.com/tommilligan/$name/releases/download/v1.8.0/$name-v1.8.0-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
        echo `pwd`/$name >> $GITHUB_PATH
    - name: Deploy GitHub Pages
      run: |
        mdbook build
        git worktree add gh-pages
        git config user.name "Deploy from CI"
        git config user.email ""
        cd gh-pages
        # Delete the ref to avoid keeping history.
        git update-ref -d refs/heads/gh-pages
        rm -rf *
        mv ../book/* .
        git add .
        git commit -m "Deploy $GITHUB_SHA to gh-pages"
        git push --force --set-upstream origin gh-pages
